
; heap size in bytes

.equ MMANAGER_ADDRESS_ZERO 						= 0x00
.equ MMANAGER_NOT_IN_USE						= 0x00
.equ MMANAGER_IN_USE							= 0x01

.equ MMANAGER_ADDRESS_DEFAULT 					= MMANAGER_ADDRESS_ZERO
.equ MMANAGER_BLOCK_SIZE_DEFAULT 				= 0x00
.equ MMANAGER_IS_IN_USE_DEFAULT 				= MMANAGER_NOT_IN_USE

.equ MMANAGER_HEAP_SIZE 						= 0x40
.equ MMANAGER_ARR_ST_HEAP_MAP_SIZE 				= MMANAGER_HEAP_SIZE * 0x03

; struct heap_map
.equ MMANAGER_ST_HEAP_MAP_ADDRES_OFFSET 		= 0x00
.equ MMANAGER_ST_HEAP_MAP_BLOCK_SIZE_OFFSET 	= 0x01
.equ MMANAGER_ST_HEAP_MAP_IS_IN_USE_OFFSET		= 0x02

.equ MMANAGER_ST_HEAP_MAP_SIZE			= 0x03

.dseg
	arr_st_heap_map:		.BYTE MMANAGER_ARR_ST_HEAP_MAP_SIZE
	arr_st_heap_map_length: .BYTE 1
	heap:					.BYTE MMANAGER_HEAP_SIZE