; constatns
; ST_CTL_BUTTON size
SZ_ST_CTL_BUTTON			= SZ_ST_CONTROL + 0x01;

; struct ST_CTL_BUTTON
ST_CTL_BUTTON_ST_BUTTON_ADDRESS_OFFSET	= ST_CONTROL_ST_DEVICE_OFFSET
ST_CTL_BUTTON_STATE_OFFSET		= SZ_ST_CONTROL

; CTL_BUTTON_STATE
CTL_BUTTON_STATE_NOT_PRESSED	= 0x00
CLT_BUTTON_STATE_PRESSED	= 0x01
