; struct st_encoder size
.equ SZ_ST_IN_BIT				= SZ_ST_DEVICE_IO
; struct st_IN_BIT
.equ ST_IN_BIT_DDRX_ADDRESS_OFFSET		= ST_DEVICE_IO_DDRX_ADDRESS_OFFSET
.equ ST_IN_BIT_PINX_ADDRESS_OFFSET 		= ST_DEVICE_IO_PINX_ADDRESS_OFFSET
.equ ST_IN_BIT_PORTX_ADDRESS_OFFSET 		= ST_DEVICE_IO_PORTX_ADDRESS_OFFSET
.equ ST_IN_BIT_USED_BIT_MASK_OFFSET		= ST_DEVICE_IO_USED_BIT_MASK_OFFSET
.equ ST_IN_BIT_TYPE_BIT_MASK_OFFSET		= ST_DEVICE_IO_TYPE_BIT_MASK_OFFSET
; encoder states
.equ IN_BIT_STATE_OFF				= 0x00
.equ IN_BIT_STATE_ON				= 0x01