; struct st_usart size
.equ SZ_ST_USART 			= SZ_ST_DEVICE_IO + 6
; struct st_usart
.equ ST_USART_DDRX_ADDRESS_OFFSET	= ST_DEVICE_IO_DDRX_ADDRESS_OFFSET
.equ ST_USART_PINX_ADDRESS_OFFSET	= ST_DEVICE_IO_PINX_ADDRESS_OFFSET
.equ ST_USART_PORTX_ADDRESS_OFFSET	= ST_DEVICE_IO_PORTX_ADDRESS_OFFSET
.equ ST_USART_USED_BIT_MASK_OFFSET	= ST_DEVICE_IO_USED_BIT_MASK_OFFSET
.equ ST_USART_TYPE_BIT_MASK_OFFSET	= ST_DEVICE_IO_TYPE_BIT_MASK_OFFSET
;
.equ ST_USART_ON_RXC_HANDLER_OFFSET	= SZ_ST_DEVICE_IO
.equ ST_USART_ON_UDRE_HANDLER_OFFSET	= SZ_ST_DEVICE_IO + 2
.equ ST_USART_ON_TXC_HANDLER_OFFSET	= SZ_ST_DEVICE_IO + 4
