; struct st_encoder size
.equ SZ_ST_BIT_INPUT				= SZ_ST_DEVICE_IO
; struct st_BIT_INPUT
.equ ST_BIT_INPUT_DDRX_ADDRESS_OFFSET		= ST_DEVICE_IO_DDRX_ADDRESS_OFFSET
.equ ST_BIT_INPUT_PINX_ADDRESS_OFFSET 		= ST_DEVICE_IO_PINX_ADDRESS_OFFSET
.equ ST_BIT_INPUT_PORTX_ADDRESS_OFFSET 		= ST_DEVICE_IO_PORTX_ADDRESS_OFFSET
.equ ST_BIT_INPUT_USED_BIT_MASK_OFFSET		= ST_DEVICE_IO_USED_BIT_MASK_OFFSET
.equ ST_BIT_INPUT_TYPE_BIT_MASK_OFFSET		= ST_DEVICE_IO_TYPE_BIT_MASK_OFFSET
; encoder states
.equ BIT_INPUT_STATE_UP				= 0x00
.equ BIT_INPUT_STATE_DOWN			= 0x01