; struct st_button size
.equ SZ_ST_BUTTON				= SZ_ST_IN_BIT
; struct st_button
.equ ST_BUTTON_DDRX_ADDRESS_OFFSET		= ST_IN_BIT_DDRX_ADDRESS_OFFSET
.equ ST_BUTTON_PINX_ADDRESS_OFFSET 		= ST_IN_BIT_PINX_ADDRESS_OFFSET
.equ ST_BUTTON_PORTX_ADDRESS_OFFSET 		= ST_IN_BIT_PORTX_ADDRESS_OFFSET
.equ ST_BUTTON_USED_BIT_MASK_OFFSET		= ST_IN_BIT_USED_BIT_MASK_OFFSET
.equ ST_BUTTON_TYPE_BIT_MASK_OFFSET		= ST_IN_BIT_TYPE_BIT_MASK_OFFSET
; encoder states
.equ BUTTON_STATE_DOWN				= IN_BIT_STATE_ON
.equ BUTTON_STATE_UP				= IN_BIT_STATE_OFF