; struct st_encoder size
.equ SZ_ST_BUTTON				= SZ_ST_DEVICE_IO
; struct st_button
.equ ST_BUTTON_DDRX_ADDRESS_OFFSET		= ST_DEVICE_IO_DDRX_ADDRESS_OFFSET
.equ ST_BUTTON_PINX_ADDRESS_OFFSET 		= ST_DEVICE_IO_PINX_ADDRESS_OFFSET
.equ ST_BUTTON_PORTX_ADDRESS_OFFSET 		= ST_DEVICE_IO_PORTX_ADDRESS_OFFSET
.equ ST_BUTTON_USED_BIT_MASK_OFFSET		= ST_DEVICE_IO_USED_BIT_MASK_OFFSET
.equ ST_BUTTON_TYPE_BIT_MASK_OFFSET		= ST_DEVICE_IO_TYPE_BIT_MASK_OFFSET
; encoder states
.equ BUTTON_STATE_UP				= 0x00
.equ BUTTON_STATE_DOWN				= 0x01