; struct st_led size: derived from st_device_io
.equ SZ_ST_LED					= SZ_ST_SWITCH
; struct st_led
.equ ST_LED_DDRX_ADDRESS_OFFSET 		= ST_SWITCH_DDRX_ADDRESS_OFFSET
.equ ST_LED_PORTX_ADDRESS_OFFSET		= ST_SWITCH_PORTX_ADDRESS_OFFSET
.equ ST_LED_USED_BIT_MASK_OFFSET		= ST_SWITCH_USED_BIT_MASK_OFFSET

.equ LED_STATE_OFF				= SWITCH_STATE_OFF
.equ LED_STATE_ON 				= SWITCH_STATE_ON