; struct st_switch size: derived from st_device_io
.equ SZ_ST_OUT_BIT				= SZ_ST_DEVICE_IO
; struct st_OUT_BIT
.equ ST_OUT_BIT_DDRX_ADDRESS_OFFSET 		= ST_DEVICE_IO_DDRX_ADDRESS_OFFSET
.equ ST_OUT_BIT_PORTX_ADDRESS_OFFSET		= ST_DEVICE_IO_PORTX_ADDRESS_OFFSET
.equ ST_OUT_BIT_USED_BIT_MASK_OFFSET		= ST_DEVICE_IO_USED_BIT_MASK_OFFSET

.equ OUT_BIT_STATE_OFF				= 0x00
.equ OUT_BIT_STATE_ON 				= 0x01