; struct st_led size
.equ SZ_ST_DEVICE_IO				= 0x08
; struct st_led
.equ ST_DEVICE_IO_DDRX_ADDRESS_OFFSET		= 0x00
.equ ST_DEVICE_IO_PINX_ADDRESS_OFFSET		= 0x02
.equ ST_DEVICE_IO_PORTX_ADDRESS_OFFSET		= 0x04
.equ ST_DEVICE_IO_USED_BIT_MASK_OFFSET		= 0x06
.equ ST_DEVICE_IO_TYPE_BIT_MASK_OFFSET		= 0x07