; struct st_switch size: derived from st_device_io
.equ SZ_ST_SWITCH				= SZ_ST_OUT_BIT
; struct st_switch
.equ ST_SWITCH_DDRX_ADDRESS_OFFSET 		= ST_OUT_BIT_DDRX_ADDRESS_OFFSET
.equ ST_SWITCH_PORTX_ADDRESS_OFFSET		= ST_OUT_BIT_PORTX_ADDRESS_OFFSET
.equ ST_SWITCH_USED_BIT_MASK_OFFSET		= ST_OUT_BIT_USED_BIT_MASK_OFFSET

.equ SWITCH_STATE_OFF				= OUT_BIT_STATE_OFF
.equ SWITCH_STATE_ON 				= OUT_BIT_STATE_ON