; struct st_switch size: derived from st_device_io
.equ SZ_ST_SWITCH				= SZ_ST_DEVICE_IO
; struct st_SWITCH
.equ ST_SWITCH_DDRX_ADDRESS_OFFSET 		= ST_DEVICE_IO_DDRX_ADDRESS_OFFSET
.equ ST_SWITCH_PORTX_ADDRESS_OFFSET		= ST_DEVICE_IO_PORTX_ADDRESS_OFFSET
.equ ST_SWITCH_USED_BIT_MASK_OFFSET		= ST_DEVICE_IO_USED_BIT_MASK_OFFSET

.equ SWITCH_STATE_OFF				= 0x00
.equ SWITCH_STATE_ON 				= 0x01