; struct st_timer size
.equ SZ_ST_TIMER0 						= SZ_ST_TIMER_BASE
.equ ST_TIMER0_COUNTER_CONTROL_REGISTER_ADDRESS_OFFSET		= ST_TIMER_BASE_COUNTER_CONTROL_REGISTER_ADDRESS_OFFSET
.equ ST_TIMER0_DIVIDER_BIT_MASK_OFFSET				= ST_TIMER_BASE_DIVIDER_BIT_MASK_OFFSET
.equ ST_TIMER0_INTERRUPT_BIT_MASK_OFFSET			= ST_TIMER_BASE_INTERRUPT_BIT_MASK_OFFSET
.equ ST_TIMER0_OVERFLOW_HANDLER_OFFSET				= ST_TIMER_BASE_OVERFLOW_HANDLER_OFFSET

; constants
