; struct st_led size: derived from st_device_io
.equ SZ_ST_LED					= SZ_ST_OUT_BIT
; struct st_led
.equ ST_LED_DDRX_ADDRESS_OFFSET 		= ST_OUT_BIT_DDRX_ADDRESS_OFFSET
.equ ST_LED_PORTX_ADDRESS_OFFSET		= ST_OUT_BIT_PORTX_ADDRESS_OFFSET
.equ ST_LED_USED_BIT_MASK_OFFSET		= ST_OUT_BIT_USED_BIT_MASK_OFFSET

.equ LED_STATE_OFF				= OUT_BIT_STATE_OFF
.equ LED_STATE_ON 				= OUT_BIT_STATE_ON