; struct st_ssi size: derived from st_out_byte
.equ SZ_ST_SSI					= SZ_ST_OUT_BYTE
; struct st_ssi:st_out_byte (inherited fields)
.equ ST_SSI_DDRX_ADDRESS_OFFSET 		= ST_OUT_BYTE_DDRX_ADDRESS_OFFSET
.equ ST_SSI_PORTX_ADDRESS_OFFSET		= ST_OUT_BYTE_PORTX_ADDRESS_OFFSET
.equ ST_SSI_USED_SSI_MASK_OFFSET		= ST_OUT_BYTE_USED_BIT_MASK_OFFSET
; struct st_ssi (new fields)
.equ ST_SSI_STATE_OFFSET			= SZ_ST_OUT_BYTE
.equ ST_SSI_SHOWN_OFFSET			= SZ_ST_OUT_BYTE + 1
.equ ST_SSI_SYMBOL_OFFSET			= SZ_ST_OUT_BYTE + 2
.equ ST_SSI_FLASH_OFFSET			= SZ_ST_OUT_BYTE + 3
.equ ST_SSI_FLASH_TIMEOUT_COUNTER_OFFSET	= SZ_ST_OUT_BYTE + 4
.equ ST_SSI_FLASH_STATE_VISIBLE_OFFSET		= SZ_ST_OUT_BYTE + 5
; enums
; SSI_STATE
.equ SSI_STATE_OFF				= 0x00
.equ SSI_STATE_ON 				= 0x01
; SSI_SHOWN
.equ SSI_SHOWN_FALSE				= 0x00
.equ SSI_SHOWN_TRUE				= 0x01
; SSI_SYMBOL
.equ SSI_SYMBOL_NULL				= 0x00
; ST_SSI_FLASH
.equ SSI_FLASH_ON				= 0x01
.equ SSI_FLASH_OFF				= 0x00
; ST_SSI_FLASH_STATE_VISIBLE
.equ SSI_FLASH_STATE_VISIBLE_FALSE		= 0x00
.equ SSI_FLASH_STATE_VISIBLE_TRUE		= 0x01
; const
.equ SSI_FLASH_TIMEOUT				= 0xff
.equ SSI_FLASH_TIMEOUT_FINISHED			= 0x00

; global const
.equ ASCII_ZERO 				= 0x30
